env: "development" # "development" | "production" | "test"
storage:
  db_driver: mysql
  db_name: database
  db_user: username
  db_password: password
  db_host: localhost
  db_port: 3301
http_server:
  port: 8080
  host: "0.0.0.0"
  timeout: 5
  iddle_timeout: 20
  shutdown_timeout: 5
security:
  pass_cost: 3
  jwt_secret: 'secret'
  jwt_refresh_secret: 'secret'