env: "development" # "development" | "production" | "test"
storage:
  db_driver: mysql
  db_name: database
  db_user: username
  db_password: password
  db_host: localhost # host for local or expenses-pg for docker
  db_port: 3301
http_server:
  port: 8080
  host: "0.0.0.0"
  timeout: 5
  iddle_timeout: 20
  shutdown_timeout: 5
security:
  pass_cost: 3
  jwt_secret: 'secret'
mail:
  host: smtp.gmail.com
  port: 587
  from: example@gmail.com
  password: pass foor apps gogl